#!/bin/sh 
SERVICE_NAME=APIMusic
PATH_TO_JAR=/root/musicapi/quanlynhac.jar
PID_PATH_NAME=/tmp/api_music
CONFIG_FILE=/root/musicapi/application.properties
JAVA_OPS="-Xms512M -Xmx1024M -server -XX:+UseParallelGC" 
 
case $1 in 
start)
       echo "Starting $SERVICE_NAME ..."
  if [ ! -f $PID_PATH_NAME ]; then 
       nohup java -Dspring.config.location=$CONFIG_FILE $JAVA_OPS -jar $PATH_TO_JAR /tmp 2>> /dev/null >>/dev/null &      
                   echo $! > $PID_PATH_NAME  
       echo "$SERVICE_NAME started ..."         
  else 
       echo "$SERVICE_NAME is already running ..."
  fi
;;
stop)
  if [ -f $PID_PATH_NAME ]; then
         PID=$(cat $PID_PATH_NAME);
         echo "$SERVICE_NAME stoping ..." 
         kill $PID;         
         echo "$SERVICE_NAME stopped ..." 
         rm $PID_PATH_NAME       
  else          
         echo "$SERVICE_NAME is not running ..."   
  fi    
;;    
restart)  
  if [ -f $PID_PATH_NAME ]; then 
      PID=$(cat $PID_PATH_NAME);    
      echo "$SERVICE_NAME stopping ..."; 
      kill $PID;           
      echo "$SERVICE_NAME stopped ...";  
      rm $PID_PATH_NAME     
      echo "$SERVICE_NAME starting ..."  
      nohup java -Dspring.config.location=$CONFIG_FILE $JAVA_OPS -jar $PATH_TO_JAR /tmp 2>> /dev/null >>/dev/null &
                   echo $! > $PID_PATH_NAME   
      echo "$SERVICE_NAME started ..."    
  else           
      echo "$SERVICE_NAME is not running ..."    
     fi     ;;
 esac


